import type { MenuCategory, MenuItem } from './types.ts'

/* Меню кафе «Марио». Состав и цены — демо: на оригинальном сайте есть только
   названия категорий (открытый вопрос 1). Категория «ЧеПронто!» сохранена
   как в оригинале, но чебуречная закрыта и блюда перешли в «Марио» —
   актуальность списка подтверждает заказчик (открытый вопрос 4). */

export const menuCategories: MenuCategory[] = [
  { slug: 'pizza', title: 'Пицца', order: 1 },
  { slug: 'pasta', title: 'Паста', order: 2 },
  { slug: 'hot', title: 'Горячие блюда', order: 3 },
  { slug: 'soups', title: 'Супы', order: 4 },
  { slug: 'salads', title: 'Салаты', order: 5 },
  { slug: 'snacks', title: 'Закуски', order: 6 },
  { slug: 'chepronto', title: 'ЧеПронто!', order: 7 },
  { slug: 'kids', title: 'Детское меню', order: 8 },
  { slug: 'desserts', title: 'Десерты', order: 9 },
  { slug: 'popcorn', title: 'Попкорн', order: 10 },
  { slug: 'drinks', title: 'Напитки', order: 11 },
  { slug: 'gift', title: 'Подарочные сертификаты', order: 12 },
]

export const menuItems: MenuItem[] = [
  {
    categorySlug: 'pizza',
    title: 'Маргарита',
    description: 'Томаты, моцарелла, базилик',
    weightG: 480,
    price: 555,
  },
  {
    categorySlug: 'pizza',
    title: 'Пепперони',
    description: 'Острая салями, моцарелла, томатный соус',
    weightG: 500,
    price: 555,
    tags: ['острое'],
  },
  {
    categorySlug: 'pizza',
    title: 'Четыре сыра',
    description: 'Моцарелла, дорблю, пармезан, чеддер, сливочный соус',
    weightG: 490,
    price: 665,
    tags: ['вегетарианское'],
  },
  {
    categorySlug: 'pizza',
    title: 'Балтийская',
    description: 'Копчёный лосось, каперсы, сливочный сыр, красный лук',
    weightG: 520,
    price: 665,
    tags: ['новинка'],
  },
  {
    categorySlug: 'pizza',
    title: 'Мясная',
    description: 'Пепперони, ветчина, бекон, куриное филе, моцарелла',
    weightG: 560,
    price: 665,
  },
  {
    categorySlug: 'pasta',
    title: 'Карбонара',
    description: 'Спагетти, бекон, сливки, желток, пармезан',
    weightG: 320,
    price: 490,
  },
  {
    categorySlug: 'pasta',
    title: 'Болоньезе',
    description: 'Тальятелле, говяжий фарш, томаты, пармезан',
    weightG: 340,
    price: 470,
  },
  {
    categorySlug: 'pasta',
    title: 'Паста с курицей и грибами',
    description: 'Пенне, куриное филе, шампиньоны, сливочный соус',
    weightG: 330,
    price: 450,
  },
  {
    categorySlug: 'hot',
    title: 'Куриное филе на гриле',
    description: 'С печёным картофелем и соусом барбекю',
    weightG: 300,
    price: 520,
  },
  {
    categorySlug: 'hot',
    title: 'Свиная шея на углях',
    description: 'С маринованным луком и томатным сальса',
    weightG: 280,
    price: 640,
  },
  {
    categorySlug: 'hot',
    title: 'Судак по-балтийски',
    description: 'Филе судака, картофельное пюре, лимонный соус',
    weightG: 290,
    price: 690,
    tags: ['новинка'],
  },
  {
    categorySlug: 'soups',
    title: 'Борщ',
    description: 'Со сметаной и пампушкой',
    weightG: 350,
    price: 320,
  },
  {
    categorySlug: 'soups',
    title: 'Куриная лапша',
    description: 'Домашняя лапша, куриное филе, зелень',
    weightG: 350,
    price: 290,
  },
  {
    categorySlug: 'soups',
    title: 'Грибной крем-суп',
    description: 'Шампиньоны, сливки, гренки',
    weightG: 300,
    price: 330,
    tags: ['вегетарианское'],
  },
  {
    categorySlug: 'salads',
    title: 'Цезарь с курицей',
    description: 'Романо, пармезан, гренки, соус цезарь',
    weightG: 240,
    price: 430,
  },
  {
    categorySlug: 'salads',
    title: 'Греческий',
    description: 'Овощи, фета, маслины, оливковое масло',
    weightG: 230,
    price: 380,
    tags: ['вегетарианское'],
  },
  {
    categorySlug: 'salads',
    title: 'Тёплый салат с говядиной',
    description: 'Говядина, микс салатов, черри, кунжутная заправка',
    weightG: 250,
    price: 490,
  },
  {
    categorySlug: 'snacks',
    title: 'Картофель фри',
    weightG: 150,
    price: 190,
    tags: ['вегетарианское'],
  },
  {
    categorySlug: 'snacks',
    title: 'Луковые кольца',
    description: 'С соусом на выбор',
    weightG: 160,
    price: 240,
    tags: ['вегетарианское'],
  },
  {
    categorySlug: 'snacks',
    title: 'Куриные крылья в остром маринаде',
    weightG: 300,
    price: 390,
    tags: ['острое'],
  },
  {
    categorySlug: 'snacks',
    title: 'Сырные палочки',
    description: 'Моцарелла в панировке, клюквенный соус',
    weightG: 180,
    price: 320,
  },
  {
    categorySlug: 'chepronto',
    title: 'Чебурек с говядиной',
    weightG: 180,
    price: 160,
  },
  {
    categorySlug: 'chepronto',
    title: 'Чебурек с сыром и зеленью',
    weightG: 170,
    price: 150,
    tags: ['вегетарианское'],
  },
  {
    categorySlug: 'chepronto',
    title: 'Чебурек с курицей и грибами',
    weightG: 180,
    price: 165,
  },
  {
    categorySlug: 'kids',
    title: 'Куриные наггетсы с картофелем',
    weightG: 220,
    price: 290,
    tags: ['детское'],
  },
  {
    categorySlug: 'kids',
    title: 'Макароны с сыром',
    weightG: 200,
    price: 220,
    tags: ['детское', 'вегетарианское'],
  },
  {
    categorySlug: 'kids',
    title: 'Молочный коктейль «Хвостатый»',
    description: 'Ваниль, клубника или шоколад',
    weightG: 300,
    price: 240,
    tags: ['детское'],
  },
  {
    categorySlug: 'desserts',
    title: 'Чизкейк',
    weightG: 130,
    price: 280,
  },
  {
    categorySlug: 'desserts',
    title: 'Штрудель с яблоком',
    description: 'С шариком пломбира',
    weightG: 180,
    price: 310,
  },
  {
    categorySlug: 'desserts',
    title: 'Медовик',
    weightG: 140,
    price: 260,
  },
  {
    categorySlug: 'popcorn',
    title: 'Попкорн солёный, средний',
    weightG: 60,
    price: 250,
  },
  {
    categorySlug: 'popcorn',
    title: 'Попкорн карамельный, средний',
    weightG: 60,
    price: 270,
  },
  {
    categorySlug: 'popcorn',
    title: 'Попкорн карамельный, большой',
    weightG: 100,
    price: 380,
  },
  {
    categorySlug: 'popcorn',
    title: 'Комбо: попкорн большой и два напитка',
    price: 590,
  },
  {
    categorySlug: 'drinks',
    title: 'Кофе',
    description: 'Эспрессо, американо, капучино, латте',
    price: 160,
  },
  {
    categorySlug: 'drinks',
    title: 'Чай листовой',
    description: 'Чёрный, зелёный, облепиховый',
    weightG: 400,
    price: 190,
  },
  {
    categorySlug: 'drinks',
    title: 'Лимонад домашний',
    description: 'Облепиха, малина или цитрус',
    weightG: 400,
    price: 220,
  },
  {
    categorySlug: 'drinks',
    title: 'Газированные напитки',
    weightG: 500,
    price: 150,
  },
  {
    categorySlug: 'gift',
    title: 'Сертификат на 1000 ₽',
    description: 'Действует на кино и кафе, срок — 6 месяцев',
    price: 1000,
  },
  {
    categorySlug: 'gift',
    title: 'Сертификат на 2000 ₽',
    description: 'Действует на кино и кафе, срок — 6 месяцев',
    price: 2000,
  },
  {
    categorySlug: 'gift',
    title: 'Сертификат на 3000 ₽',
    description: 'Действует на кино и кафе, срок — 6 месяцев',
    price: 3000,
  },
]
